services:
  - type: web
    name: evilworker
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    buildCommand: docker build -t evilworker .
    startCommand: docker run -p $PORT:3000 evilworker
